Upgrade Elixir and OTP
open-telemetry/opentelemetry-erlang pull request #254
Opened 2021-05-31 02:22 UTC by wingyplus

This change do:

* Add Elixir 1.12.1 and upgrade 1.11 to latest release.
* Add OTP 24.0.1 and upgrade major OTP release to latest release.
* Drop OTP 21.

2021-05-31 13:14 UTC, hauleth approved these changes

2021-05-31 13:22 UTC, hauleth commented
Why remove OTP 21?

2021-05-31 13:23 UTC, hauleth requested changes

2021-05-31 13:23 UTC, hauleth commented on .github/workflows/elixir.yml
> +        otp_version: ['24.0.1', '23.3.4.1', '22.3.4.19']
As we are supporting Elixir 1.11 we shouldn't remove OTP 21 from matrix, just ignore such set of options.

2021-05-31 13:26 UTC, wingyplus commented
> Why remove OTP 21?

The discussion is in #253. And Elixir 1.12 requires to run OTP 21 or greater.  That’s why I decide to drop it. Or do you have any suggestions?

2021-05-31 13:33 UTC, hauleth commented
We can exclude only Elixir 1.12 and OTP 21 and still run them - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-excluding-configurations-from-a-matrix

2021-05-31 13:39 UTC, wingyplus commented
> We can exclude only Elixir 1.12 and OTP 21 and still run them - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-excluding-configurations-from-a-matrix

@hauleth Thanks for your suggestion. Do you mind if I upgrade to 21.3.8.23?

2021-05-31 13:40 UTC, hauleth commented
Not at all.

2021-05-31 13:47 UTC, wingyplus commented
The OTP 21 is added back to the CI on both Elixir and OTP workflow. Please kindly review.

2021-05-31 19:52 UTC, hauleth approved these changes

2021-06-01 01:32 UTC, wingyplus commented
I’ve found similar issue with #253. Not sure why it happens.

```
escript: exception error: undefined function rebar3:main/1
8
  in function  escript:run/2 (escript.erl, line 758)
9
  in call from escript:start/1 (escript.erl, line 277)
10
  in call from init:start_em/1 
11
  in call from init:do_boot/3 
12
Error: Process completed with exit code 127.
```

2021-06-01 11:49 UTC, tsloughter commented
I thought it was because of rebar3 only being built on recent otp's now (otp-24 dropped deprecated stuff so couldn't use older builds with it). But I Thought 21 was new enough...

@ferd ?

2021-06-01 11:54 UTC, ferd commented
We used the opportunity of clamping down on the rebar3 vs OTP compatibility window to just line up directly with what the OTP team supports all at once rather than doing it progressively, with the rationale that OTP24's JIT would provide enough of an incentive.

Versions 3.16.x are 22..24 so far.

2021-06-01 12:13 UTC, wingyplus commented
@ferd i see in you mentioned in the blog (https://ferd.ca/you-ve-got-to-upgrade-rebar3.html) that 3.15.2 support OTP 19-23. Can we use that one?

I just see that setup-beam allow us to set rebar3 version (https://github.com/erlef/setup-beam#matrix-example-rebar3). So if we want to keep otp21, we might set the rebar3 to 3.15.2 to the pipeline and use the latest version for otp 22+.

And I notice that erlef change to setup-beam. Do you need me to change it instead of setup-elixir?

2021-06-01 12:17 UTC, ferd commented
There's no reason it wouldn't work to use 3.15.2 for OTP-21 specifically. We cut the security release on that one specifically to still provide support as far back as posslbe (and eventually added 13.3.x with user contribs as well for people either needing older behaviour or OTP-18). 

For a while this will be plenty, but over time the differences may accumulate and cause divergences.

2021-06-01 13:38 UTC, tsloughter commented
Aaah, 22, not 21.

2021-06-01 14:22 UTC, wingyplus commented
@tsloughter @hauleth I have a fix for OTP 21 issue by using OTP 21 with rebar3 3.15.2 instead. Please kindly review.

2021-06-01 19:49 UTC, hauleth approved these changes

2021-06-01 20:57 UTC, ferd commented
Is it normal that the 4 checks that passed don't contain Erlang?

Looking at the checks I can see the following is broken for Erlang: https://github.com/open-telemetry/opentelemetry-erlang/actions/runs/896362703
![image](https://user-images.githubusercontent.com/111141/120389396-5c3c4b80-c2fa-11eb-9275-65af63141a27.png)
And for Elixir:
![image](https://user-images.githubusercontent.com/111141/120389425-65c5b380-c2fa-11eb-8da9-42383bdf67b2.png)

I think we can't merge this, it appears the CI is broken but still showing as 4 successful checks.

2021-06-01 20:58 UTC, ferd requested changes
The CI steps appear to still be broken.

2021-06-02 00:30 UTC, wingyplus commented
Umm, if i understand it correctly. The run-on empty because I forget adding os into the include.

Let me investigate.

2021-06-02 02:50 UTC, wingyplus commented
I've added `os` into the include matrix. This should fix the problem can we try to trigger the pipeline?

2021-06-02 12:56 UTC, ferd commented
Done, it seems to be running them all now.

2021-06-02 13:36 UTC, wingyplus commented
@ferd Thanks for your help. It's because I accidentally change Elixir to 1.12 in Erlang dialyzer which does not require since change to setup-beam. And I found the `matrix.elixir` variable is inconsistent, which cause the wrong test name. 

All of this should fixed in latest changes.

2021-06-02 13:37 UTC, ferd approved these changes
Everything seems to work successfully now, let's get this merged!

2021-06-02 13:37 UTC, merged

2021-06-02 13:38 UTC, wingyplus commented
@hauleth @ferd @tsloughter Thanks for your help. :)

2021-06-02 17:50 UTC, hauleth commented
💚 💙 💜 💛 ❤️