Do not insert non-recording spans in ETS
open-telemetry/opentelemetry-erlang pull request #267
Opened 2021-08-11 13:52 UTC by dvic

2021-08-11 16:21 UTC, tsloughter commented
Thanks.

So yea, I still can't find a reason we'd need or want to store this span in ets.

Event `otel_span` functions ignore calls on spans that are not recording, so the table is never updated.

2021-08-11 18:27 UTC, bryannaegele commented
Probably wouldn't hurt to add a non-recording span case in https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry/test/opentelemetry_SUITE.erl#L149

2021-08-11 19:07 UTC, tsloughter requested changes

2021-08-11 19:07 UTC, tsloughter commented on apps/opentelemetry/src/otel_span_ets.erl
> +            %% _ = storage_insert(Span),
```suggestion
```

2021-08-11 19:07 UTC, tsloughter commented on apps/opentelemetry/src/otel_span_ets.erl
>              %% but we do insert to ets table?
```suggestion
            %% span isn't recorded so don't run processors or insert into ets table
```

2021-08-12 17:54 UTC, dvic commented
@tsloughter I applied your suggestions and rebased into one commit.

2021-08-12 18:09 UTC, dvic commented
I've added a simple test case.

2021-08-19 23:42 UTC, tsloughter approved these changes

2021-08-19 23:42 UTC, merged