Expose trace IDs in hex format
open-telemetry/opentelemetry-erlang pull request #270
Opened 2021-09-01 13:29 UTC by indrekj

According to the [spec][1]
> The API MUST allow retrieving the TraceId and SpanId in the following forms:
>
>  *  Hex - returns the lowercase hex-encoded TraceId (result MUST be a 32-hex-character lowercase string) or SpanId (result MUST be a 16-hex-character lowercase string).
>  *  Binary - returns the binary representation of the TraceId (result MUST be a 16-byte array) or SpanId (result MUST be an 8-byte array).
>
> The API SHOULD NOT expose details about how they are internally stored.

This commit takes care of the Hex part.

[1]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#retrieving-the-traceid-and-spanid)

2021-09-01 14:28 UTC, tsloughter requested changes
Since the spec requires the trace id to be 32 characters and the span id to be 16 characters the `integer_to_binary` function can't be used -- or  at least can't be used without also adding padding to the beginning of the string. My suggested change is using `io_lib:format` to get a string of the correct length that is in hex.

2021-09-01 14:28 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_span.erl
> +    string:lowercase(integer_to_binary(TraceId, 16)).
```suggestion
    io_lib:format("~32.16.0b", [TraceId]).
```

2021-09-01 14:28 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_span.erl
> +    string:lowercase(integer_to_binary(SpanId, 16)).
```suggestion
    io_lib:format("~16.16.0b", [SpanId]).
```

2021-09-01 14:28 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_span.erl
> +hex_span_id(#span_ctx{span_id=SpanId }) ->
```suggestion
hex_span_id(#span_ctx{span_id=SpanId}) ->
```

2021-09-01 14:28 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_span.erl
> +hex_trace_id(#span_ctx{trace_id=TraceId }) ->
```suggestion
hex_trace_id(#span_ctx{trace_id=TraceId}) ->
```

2021-09-01 14:32 UTC, tsloughter commented
Thanks!

My initial thought was an api like `otel_span:trace_id(Span, Format)` might be nicer -- where `trace_id/1` would call `trace_id(Span, integer)`... but maybe not since we are unlikely to have to expose more than hex and binary formats.

2021-09-01 15:20 UTC, indrekj commented on apps/opentelemetry_api/src/otel_span.erl
> +    string:lowercase(integer_to_binary(TraceId, 16)).
Good catch. I forgot that completely. https://github.com/open-telemetry/opentelemetry-erlang/compare/a19f1a44c1e63f969b87d34fe1e690994cb8767e..a97f5b7f3a034057a542bcde7be1a925ef169184

2021-09-01 15:20 UTC, indrekj commented on apps/opentelemetry_api/src/otel_span.erl
> +    string:lowercase(integer_to_binary(SpanId, 16)).
https://github.com/open-telemetry/opentelemetry-erlang/compare/a19f1a44c1e63f969b87d34fe1e690994cb8767e..a97f5b7f3a034057a542bcde7be1a925ef169184

2021-09-01 15:20 UTC, indrekj commented on apps/opentelemetry_api/src/otel_span.erl
> +hex_span_id(#span_ctx{span_id=SpanId }) ->
https://github.com/open-telemetry/opentelemetry-erlang/compare/a19f1a44c1e63f969b87d34fe1e690994cb8767e..a97f5b7f3a034057a542bcde7be1a925ef169184

2021-09-01 15:20 UTC, indrekj commented on apps/opentelemetry_api/src/otel_span.erl
> +hex_trace_id(#span_ctx{trace_id=TraceId }) ->
https://github.com/open-telemetry/opentelemetry-erlang/compare/a19f1a44c1e63f969b87d34fe1e690994cb8767e..a97f5b7f3a034057a542bcde7be1a925ef169184

2021-09-01 15:21 UTC, indrekj commented on apps/opentelemetry_api/src/otel_span.erl
> +    string:lowercase(integer_to_binary(TraceId, 16)).
Also added a test for that.

2021-09-01 15:28 UTC, indrekj commented
> but maybe not since we are unlikely to have to expose more than hex and binary formats

I don't have a strong opinion. I followed how it was done in [ruby](https://github.com/open-telemetry/opentelemetry-ruby/blob/cc28b8648e4085ff62e65e3db87ff45f82750cd1/api/lib/opentelemetry/trace/span_context.rb#L38-L50), but it seems that different language implementations do it differently (e.g. [python](https://github.com/open-telemetry/opentelemetry-python/blob/3fdfa6d6fbbb26e866ab8d40dc62ef1b4295ffc4/opentelemetry-api/src/opentelemetry/trace/span.py#L558-L577), [java](https://github.com/open-telemetry/opentelemetry-java/blob/d9ab761ea9a00381816a05d7feef08c61a06822d/api/all/src/main/java/io/opentelemetry/api/trace/SpanContext.java#L89-L95).

2021-09-07 16:27 UTC, tsloughter approved these changes

2021-09-21 17:00 UTC, merged