add simple span processor
open-telemetry/opentelemetry-erlang pull request #304
Opened 2021-11-03 23:43 UTC by tsloughter

The Simple Span Processor does a blocking call when ending a span
that returns after the span is exported.

2021-11-03 23:45 UTC, tsloughter commented
Opened as a draft since it still needs some docs and I don't like that both processors are started in the supervisor no matter what (but that may be acceptable for now).

2021-11-05 17:18 UTC, ferd requested changes

2021-11-05 17:18 UTC, ferd commented on apps/opentelemetry/src/otel_simple_processor.erl
> +     [{state_timeout, ExportingTimeout, exporting_timeout}]};
This implies that the events have individual timeouts for their send time, which ignores the queuing time. Is this accurate? I'm unfamiliar with the spec here.

But let's assume this is correct, then the desired behaviour, if I have process A and processes B sending a synchronous span at once, and both hit a connection timeout of 2 seconds, would mean that A would wait ~2 seconds, and B would wait ~4 seconds before returning.

2021-11-05 17:18 UTC, ferd commented on apps/opentelemetry/src/otel_simple_processor.erl
> +     [{reply, From, ok}]}.
I guess here we can already have sent the timeout result. The gen_statem module however supports a way to use a proxy process to hide the dirty messages:

https://github.com/erlang/otp/blob/b3d4affcf9880255f6edc2e67095015e6ed2aca2/lib/stdlib/src/gen_statem.erl#L591-L596

Doing so would recommend using the option `{clean_timeout, infinity}` in `gen_statem:call/3`, which would set up a proxy process to ignore the duplicate messages. You might want to either use that, or make a special non-replying `complete_exporting/1` function acknowledge timeout races and prevents sending two replies to a single call.

2021-11-05 19:47 UTC, tsloughter commented on apps/opentelemetry/src/otel_simple_processor.erl
> +     [{state_timeout, ExportingTimeout, exporting_timeout}]};
It is unrelated to the queue time, correct. This is a configuration on the processor to kill the exporter if it takes too long. I punted on a client side timeout that can be passed for now -- I think its possible to do it decently now with `send_request` or whatever it is that ensures old replies aren't a problem.

2021-11-05 19:50 UTC, tsloughter commented on apps/opentelemetry/src/otel_simple_processor.erl
> +     [{reply, From, ok}]}.
Oh, thanks. I might use that, but this made me realize, don't I just need to set `current_from` to `undefined` in the timeout reply (which it currently isn't doing and is a bug)?

Then `complete_exporting` can not send a reply if the `current_from` is `undefined`.

2021-11-05 19:57 UTC, ferd commented on apps/opentelemetry/src/otel_simple_processor.erl
> +     [{reply, From, ok}]}.
Actually, not right now, unless you have a way to either cancel the state timeout, or to change the state. As this is implemented right now, we set the timer, complete, stay in the same state. 

So we're likely to hit an invalid leftover state timeout if there is a decent time between requests, such that sending one span, succeeding, responding okay, then waiting N seconds will still trigger a timeout message. The timeout is never cancel, the state never changes, so the state timeout should fire at some point. I'm not 100% what's the behaviour if you set a state timeout, then set a new one, whether that cancels the old state timeout or just adds more.

2021-11-05 20:00 UTC, tsloughter commented on apps/opentelemetry/src/otel_simple_processor.erl
> +     [{reply, From, ok}]}.
Wait no, it repeats the state and is supposed to retry, so it can't set `current_from` to `undefined`... grr

2021-11-05 20:18 UTC, tsloughter commented on apps/opentelemetry/src/otel_simple_processor.erl
> +     [{reply, From, ok}]}.
Yup, realized that after replying. 

Setting the state timeout does cancel and create a new one though.

2021-11-05 22:24 UTC, tsloughter commented on apps/opentelemetry/src/otel_simple_processor.erl
> +     [{reply, From, ok}]}.
Bleh, also, why am I sending an error if it repeats. Need to either not repeat or not return an error.

2021-11-05 23:08 UTC, tsloughter commented on apps/opentelemetry/src/otel_simple_processor.erl
> +     [{reply, From, ok}]}.
Updated to transition to idle.

`repeat` was used in batch processor to do another export of newly ended spans that have been waiting while the current exporting was blocking them from being exported.

I realize now that might be the wrong way to go about since there should be an export timeout message in the queue since we postpone it if in the exporting state, so there should be no need to repeat the state. But I'll want to verify my thinking again on that and send a separate PR.

2021-11-06 00:58 UTC, ferd approved these changes

2021-11-06 11:51 UTC, merged