move zipkin exporter to main repo
open-telemetry/opentelemetry-erlang pull request #325
Opened 2021-11-29 22:47 UTC by tsloughter

2021-11-30 14:19 UTC, ferd requested changes

2021-11-30 14:19 UTC, ferd commented on apps/opentelemetry_zipkin/README.md
> +![](https://github.com/opentelemetry-beam/opentelemetry_zipkin/workflows/OpenTelemetry%20Zipkin%20Tests/badge.svg)
I figure this is where we're moving it from; the badge is unlikely to remain functional.

2021-11-30 14:19 UTC, ferd commented on apps/opentelemetry_zipkin/src/opentelemetry_zipkin.app.src
> +  {links, [{"GitHub", "https://github.com/opentelemetry-beam/opentelemetry_zipkin"}]}
This will no longer be true

2021-11-30 14:19 UTC, ferd commented on apps/opentelemetry_zipkin/test/opentelemetry_zipkin_SUITE.erl
> +    ?assertMatch(ok, opentelemetry_zipkin:export(Tid, Resource, State)),
this line's failing in the tests, returning `error` only. This seems to be due to the http call itself failing (or returning an unknown status), but we can't see which of the two potential log lines (error response or client error) got triggered.

2021-11-30 16:19 UTC, tsloughter commented on apps/opentelemetry_zipkin/test/opentelemetry_zipkin_SUITE.erl
> +    ?assertMatch(ok, opentelemetry_zipkin:export(Tid, Resource, State)),
hm, damn, ok. It is passing locally and both local and github actions use the same docker compose file. But it must be something to do with the zipkin services it is trying to export to.

2021-12-17 17:02 UTC, tsloughter commented
@ferd this should be good to go now.

2021-12-17 20:32 UTC, ferd approved these changes

2021-12-18 02:40 UTC, merged