Remaining validations
open-telemetry/opentelemetry-erlang pull request #332
Opened 2021-12-25 00:12 UTC by bryannaegele

This adds validations and limits attribute values to those in the spec rather than what the protos are capable of exporting. I've also added validation to span start opts which were previously not being validated in any way.

There's a second commit here that removes validations and tracking attribute validation drops at the SDK level. Looking through the spec, [this section](https://github.com/open-telemetry/opentelemetry-specification/blob/9216eb8ff1832ae790369e49ce326cb6bc3d1c80/specification/trace/sdk.md?plain=1#L127-L129) indicates the dropped attribute count is tracking attributes dropped due to count limits. This makes sense to me since validation and allowed types are an API-level concern which aren't trackable, whereas system limits are an SDK-level concern which is trackable.

We can try to get some verification on that one.

Closes #323

2021-12-25 00:53 UTC, bryannaegele commented
Crap. Just realized `filtermap` is an OTP 24 introduction :/

2021-12-25 13:01 UTC, tsloughter commented
@bryannaegele filtermap is from R16

2021-12-25 13:07 UTC, tsloughter commented on apps/opentelemetry/src/otel_attributes.erl
> +%% already in the map and not a binary so update
Why adding anything that isn't a binary?

2021-12-25 16:43 UTC, bryannaegele commented on apps/opentelemetry/src/otel_attributes.erl
> +%% already in the map and not a binary so update
The API will have already filtered out everything in the validation step before getting to the SDK, so it should only need to possibly truncate a binary value if it exceeds the length limit.

2021-12-25 16:45 UTC, tsloughter commented on apps/opentelemetry/src/otel_attributes.erl
> +%% already in the map and not a binary so update
Ah, gotcha.

One thing I forgot to do and I don't think I see here is also limiting the length of an list (array). Think you can sneak that in here? If no I'll open a separate PR after this gets merged.

2021-12-25 16:52 UTC, bryannaegele commented
> @bryannaegele filtermap is from R16

Yeah, was referring to the `maps:filtermap` which was more recent. I didn't need to be using that anyhow since there was no transform.

One questionable thing I did was returning `undefined` on invalid names. I didn't want to raise and the only other alternative would be to have some placeholder, but in a `with_span` then that `undefined` would get passed to `end_span` which presently doesn't handle that; it always expects a span ctx. We can start handling `undefined` on `end_span` or raise on the name. Thus far, we've generally stayed quiet on errors but maybe this calls for it.

2021-12-25 16:55 UTC, bryannaegele commented on apps/opentelemetry/src/otel_attributes.erl
> +%% already in the map and not a binary so update
Yeah, I thought there was something for that in the spec but I couldn't find it. Is it a separate value from the binary limit?

2021-12-25 16:58 UTC, tsloughter commented on apps/opentelemetry/src/otel_attributes.erl
> +%% already in the map and not a binary so update
Na, same limit. I'll go look for it in the spec, I'm pretty sure its there somewhere.

2021-12-25 17:00 UTC, tsloughter commented on apps/opentelemetry/src/otel_attributes.erl
> +%% already in the map and not a binary so update
Oh, well first I guess, is each string in an array has to be truncated:

> if it is an array of strings, then apply the above rule to each of the values separately,

2021-12-25 17:31 UTC, bryannaegele commented on apps/opentelemetry/src/otel_attributes.erl
> +%% already in the map and not a binary so update
Yeah but are we going to enforce that? I thought we decided to not validate or mess with list contents due to the perf hit. I guess since it's a resources protection issue, maybe we have to do it anyhow. At that point, I may as well go ahead and add the array homogeneity checks, too.

Up to you. If it's a real drag on performance we could add an opt-out option later, I suppose. I'd be a little surprised if folks had many lists or that they'd be lengthy enough to be truly impactful.

2021-12-25 17:33 UTC, bryannaegele commented on apps/opentelemetry/src/otel_attributes.erl
> +%% already in the map and not a binary so update
Iterating a list of binaries and checking their length is probably the worst possible perf iteration we could do, so makes sense to just add everything if we're already making that possible.

2021-12-25 18:57 UTC, tsloughter commented on apps/opentelemetry/src/otel_attributes.erl
> +%% already in the map and not a binary so update
It is in the spec as a requirement if we support limits, so yea, we should have it.

We can document to a user that if they want to avoid these iterations they can set the length limit to infinity. We could check homogeneity only when it isn't infinity for length. Possibly a bit odd behavior to some but simple to document. And the issue of wanting to drop before the exporter (where it'll be dropped if it isn't homogeneous) is only an issue if they add too many attributes that they hit the limit and then want latter attributes to still be included since those should have been dropped... so I don't think its a big deal.

2021-12-26 02:19 UTC, tsloughter commented
Oh, missed the part about raising. Na, should never raise. Should create a zero span where all id's are 0.

2021-12-26 02:19 UTC, tsloughter commented
And `is_valid` `is_recording` are false:

```
-define(NOOP_SPAN_CTX, #span_ctx{trace_id=0,
                                 span_id=0,
                                 trace_flags=0,
                                 tracestate=[],
                                 is_valid=false,
                                 is_recording=false,
                                 span_sdk=undefined}).
```

2021-12-26 12:22 UTC, tsloughter commented on apps/opentelemetry/src/otel_attributes.erl
> +    Attributes#attributes{map=Map#{Key => Value}};
```suggestion
    Attributes#attributes{map=Map#{Key := Value}};
```

This might be more efficient since we know the key is there.

2021-12-26 12:23 UTC, tsloughter commented on apps/opentelemetry/test/opentelemetry_SUITE.erl
> +    ?set_attribute(<<"attr-2-dropped">>, {non_homogenous, <<"attributes">>}),
Can you add a test to show that a homogenous tuple is accepted?

2021-12-26 12:34 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_span.erl
> +is_valid_attribute(Key, [Value1 | _Rest] = Values) when is_binary(Value1) , ?is_allowed_key(Key) ->
```suggestion
%% lists as attribute values must be primitive types and homogeneous
is_valid_attribute(Key, [Value1 | _Rest] = Values) when is_binary(Value1) , ?is_allowed_key(Key) ->
```

Just thought a comment here would be helpful for the future.

2021-12-26 12:36 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_tracer.erl
> +                    opentelemetry:span_name(), otel_span:start_opts(), traced_fun(T)) -> T | any().
Why adding `any()` here?

2021-12-26 12:39 UTC, tsloughter requested changes

2021-12-26 12:39 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_tracer.erl
> +-spec with_span(opentelemetry:tracer(), opentelemetry:span_name(), otel_span:start_opts(), traced_fun(T)) -> T | any().
Same with the `any()` here.

2021-12-26 12:39 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_tracer.erl
> +            Fun()
`Fun` is arity 1, need to pass a noop span here.

2021-12-26 12:39 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_tracer.erl
> +            undefined
As discussed on slack, I think this should return the `?NOOP_SPAN_CTX` from `otel_tracer_noop`. I need to verify in the spec, but I'm not sure what else it could return.

2021-12-26 18:33 UTC, bryannaegele commented on apps/opentelemetry/test/opentelemetry_SUITE.erl
> +    ?set_attribute(<<"attr-2-dropped">>, {non_homogenous, <<"attributes">>}),
There's one in the API validations test [here](https://github.com/open-telemetry/opentelemetry-erlang/pull/332/files#diff-81ca87e336303c4f98ee125fabcd666912e558b3761db01845298907fb44cb84R84) but I can add a second one there.

2021-12-26 18:41 UTC, tsloughter commented on apps/opentelemetry/test/opentelemetry_SUITE.erl
> +    ?set_attribute(<<"attr-2-dropped">>, {non_homogenous, <<"attributes">>}),
Oh yea, ok, no need then.

2021-12-26 18:53 UTC, bryannaegele commented on apps/opentelemetry_api/src/otel_tracer.erl
> +                    opentelemetry:span_name(), otel_span:start_opts(), traced_fun(T)) -> T | any().
I think I added that from the `undefined` return. Shouldn't be needed. Same with those undefineds.

2021-12-26 19:02 UTC, bryannaegele commented on apps/opentelemetry/test/opentelemetry_SUITE.erl
> +    ?set_attribute(<<"attr-2-dropped">>, {non_homogenous, <<"attributes">>}),
Nah. It was definitely needed. Missed a check on the singular `set_attribute/3` so there was a bug 😆

2021-12-26 19:07 UTC, tsloughter commented on apps/opentelemetry/test/opentelemetry_SUITE.erl
> +    ?set_attribute(<<"attr-2-dropped">>, {non_homogenous, <<"attributes">>}),
Ah ok, hehe.

Reminds me, should have a test for a bad span name when calling `with_span`. Since that would have caught the fact it was calling `Fun()` instead of `Fun(SpanCtx)`.

2021-12-26 23:31 UTC, tsloughter approved these changes

2021-12-26 23:31 UTC, merged