Fix OTLP Protocol allowed values
open-telemetry/opentelemetry-erlang pull request #420
Opened 2022-08-10 16:31 UTC by andrewhr

As the [specification describes][1], there are 3 possible values for ENV vars that set the OTLP protocol used by OTLP exporter:
- grpc
- http/protobuf
- http/json

The SDK implementation leans on `list_to_existing_atom` function, so our expected values are in fact `http_protobuf` instead of `http/protobuf` for example.

This is confusing for ones following the generic documentation, and also may become a problem in polyglot environments: let's say, I share the same ENV setup for a Java and Erlang application.

The fix here account for the current atom values, and strings with the same snake_case format for backwards compatibility. But also accept the standard approach.

The fix includes `http/json` as possible transform, but the exporter will still fails as that isn't supported by our impl.

[1]: https://github.com/open-telemetry/opentelemetry-specification/blob/82707fd9f7b1266f1246b02ff3e00bebdee6b538/specification/protocol/exporter.md#specify-protocol

2022-08-10 22:54 UTC, tsloughter approved these changes
Thanks! I could have swore I had already done this!

2022-08-10 22:58 UTC, tsloughter commented on apps/opentelemetry/src/otel_configuration.erl
> +  http_json;
Oops, approved too soon. We need a log here and I'd propose falling back to `http_protobuf`.

I know Ruby doesn't support grpc, so could see what they do if the protocol is set to grpc and do the same.

2022-08-10 22:59 UTC, tsloughter requested changes
Changing to requesting changes.

2022-08-18 15:27 UTC, andrewhr commented on apps/opentelemetry/src/otel_configuration.erl
> +  http_json;
[The Agent defalts to none and logs a warning](https://github.com/open-telemetry/opentelemetry-ruby/blob/5b0cee9678badba6e332b380d532d5f4dcd1714a/sdk/lib/opentelemetry/sdk/configurator.rb#L181-L188)

I replicated their behaviour here. I believe the rationale is something in the lines "if I expect something different from HTTP/Protobuf, it will fail anyway". Seems a sensible approach to me, what do you think Tristan?

2022-08-18 16:22 UTC, tsloughter commented on apps/opentelemetry/src/otel_configuration.erl
> +  http_json;
The warning looks good, but we need a catch all for cases the string is not one of the values we expect. I think `undefined` should be used instead of `none`. We use `none` for setting no exporter, so prefer to just use `undefined` for a wrong protocol. 

Also, `opentelemetry_exporter:init/1` will crash in the case on line 165, it needs to return I guess `{ok, #state{protocol=undefined}}` when protocol is `undefined`.

2022-08-23 22:41 UTC, tsloughter commented
@andrewhr there is a test failure. Looks like it just needs `assertEqual` changed to `assertMatch`.

2022-09-13 19:41 UTC, andrewhr commented
@tsloughter sorry for the delay. I'm not that familiar with Erlang testing and have some issues running locally. So I just changed to `assertMatch` as you suggested 🤞

2022-09-13 21:15 UTC, tsloughter approved these changes

2022-09-13 21:17 UTC, tsloughter commented on apps/opentelemetry_exporter/test/opentelemetry_exporter_SUITE.erl
> +        ?assertMatch(#{endpoints =>
Match needs to use `:=`

Erlang distinguishes matching `:=` and creating `=>` in maps.

2022-09-14 15:06 UTC, andrewhr commented
Thanks for explaining me how `assertMatch` works in Erlang. I rewrote the tests to just check the protocol now, via match. I get to run locally by mimic of Github commands. I think we're good!

Sorry for the noise in the meantime 🙇

2022-09-14 22:24 UTC, merged