Logging Handler
open-telemetry/opentelemetry-erlang pull request #468
Opened 2022-09-23 23:38 UTC by tsloughter

This is a very simple version of what is needed to support the logging spec and is in part duplicating code from the batch span processor.

It has no overload protection and this will wait until we know what is planned for log sampling in the spec as it will overlap.

Oh, and no tests. I've only manually tested by bringing up the collector and a rebar3 shell in which I add the handler and then see logs going to the collector through the collector's console output where it will log each log it receives.

2022-09-27 14:48 UTC, ferd requested changes

2022-09-27 14:48 UTC, ferd commented on apps/opentelemetry_exporter/src/opentelemetry_exporter.erl
> +            ?LOG_INFO("OTLP grpc export failed with error: ~p", [Reason]),
is there any chance these logs messages are gonna be fed back into the OTel exporter and cause issues with write amplification?

2022-09-27 14:48 UTC, ferd commented on apps/opentelemetry_exporter/src/otel_otlp_common.erl
> +    case io_lib:printable_list(Value) of
This is a tricky thing because it relies on the `+pc <unicode|latin1>` value to work. `io_lib:printable_range/0` will define what you get. 

You want to use `io_lib:printable_unicode_list(Value)` here, which will assume unicode output and tell you if that unicode output is printable or not. I had code for the `flatlog` library in tests that ended up looking like:

```erlang
case io:printable_range() of
    latin1 -> io_lib:printable_list(S);
    unicode -> io_lib:printable_unicode_list(S)
end
``` 

Since we're shuttling bytes over the network and we don't care about whether the VM is configured to use only unicode or not, we should just flat out do as the docstring says, assume UTF8, and call `io_lib:printable_unicode_list(S)` here.

2022-09-27 14:48 UTC, ferd commented on apps/opentelemetry_exporter/src/otel_otlp_common.erl
> +            #{value => {string_value, unicode:characters_to_binary(Value)}};
This may return a non-string value. Is this okay? Unicode conversion can return:

> [binary()](https://www.erlang.org/doc/man/erlang.html#type-binary) |
    {error, [binary()](https://www.erlang.org/doc/man/erlang.html#type-binary), RestData} |
    {incomplete, [binary()](https://www.erlang.org/doc/man/erlang.html#type-binary), [binary()](https://www.erlang.org/doc/man/erlang.html#type-binary)}

2022-09-27 14:48 UTC, ferd commented on apps/opentelemetry_exporter/src/otel_otlp_logs.erl
> +                    re:replace(T,",?\r?\n\s*",", ",
if I'm reading this right, if you have two linebreaks this will leave one behind. You likely want `(?:\r\n|\n|\s)+` as a group for the linebreaks. Also since you're using `,?` and then replacing with `, `, this may inject commas into logs. To keep it the same we probably want to use `(,?)` and reinject that capture group.

This looks a bit like:

```
1> re:replace("a, \r\n  b  \n\n  c,d, e f  ", "(,?)(\\r\\n|\\n|\\s)+", "\\g{1} ", [global, {return, list}]).
"a, b c,d, e f "
``` 
which preserves the original meaning but collapses duplicated whitespace.

2022-09-27 15:27 UTC, tsloughter commented on apps/opentelemetry_experimental/src/otel_log_handler.erl
> +         report_cb/1]).
These are OTP logger handler callbacks.

2022-09-27 15:28 UTC, tsloughter commented on apps/opentelemetry_experimental/src/otel_log_handler.erl
> +         report_cb/1]).
And note it is "adding_handler" and such because it doesn't actually do the "add".  It is the callback you get called when the handler is added, the actual add is done in OTP.

2022-09-27 15:28 UTC, tsloughter commented on apps/opentelemetry_experimental/src/otel_log_handler.erl
> +    {keep_state, Data, [{reply, From, Config}]};
Na, it is supposed to return with the Config being used.

2022-09-27 15:29 UTC, tsloughter commented on apps/opentelemetry_experimental/src/otel_log_handler.erl
> +            true
I wasn't considering it retryable is why I did `true`. Since it'd be something like a protobuf encoding exception.

2022-09-27 15:31 UTC, tsloughter commented on apps/opentelemetry_experimental/src/otel_log_handler.erl
> +    _ = export(Exporter, Resource, Batch, Config),
Interesting idea... I planned to simplify it by breaking out the shared logic from the `batch_processor` module. If that works there too then it makes sense to do.

2022-09-27 15:32 UTC, tsloughter commented on apps/opentelemetry_exporter/src/otel_otlp_common.erl
> +    case io_lib:printable_list(Value) of
Ah, yea, we do want always to do `io_lib:printable_unicode_list(S)` because that is required by the protocol. So I'll update to that.

2022-09-27 15:33 UTC, tsloughter commented on apps/opentelemetry_exporter/src/otel_otlp_common.erl
> +            #{value => {string_value, unicode:characters_to_binary(Value)}};
I always forget about that. I'll fix it, think it needs to be an exception and drop this value if it fails.

2022-09-27 15:36 UTC, tsloughter commented on apps/opentelemetry_exporter/src/otel_otlp_logs.erl
> +                    re:replace(T,",?\r?\n\s*",", ",
I took this from logger https://github.com/erlang/otp/blob/master/lib/kernel/src/logger_formatter.erl#L75-L84

2022-09-27 17:02 UTC, ferd commented on apps/opentelemetry_experimental/src/otel_log_handler.erl
> +         report_cb/1]).
oh well there goes my memory of how to implement this stuff. Disregard then.

2022-09-27 17:03 UTC, ferd commented on apps/opentelemetry_exporter/src/otel_otlp_logs.erl
> +                    re:replace(T,",?\r?\n\s*",", ",
alright, that works then. Getting consistency in.

2022-09-27 18:09 UTC, tsloughter commented on apps/opentelemetry_exporter/src/otel_otlp_common.erl
> +    case io_lib:printable_list(Value) of
Updated. I also updated how binary strings are encoded to work properly with the spec. If the binary is not found to be a unicode string it is encoded as a `bytes_value` now.

2022-09-28 14:32 UTC, ferd approved these changes
Major concerns addressed. Still curious about the logging handler failing and possibly generating more logs to handle and the risk this might represent.

2022-09-28 21:42 UTC, tsloughter commented on apps/opentelemetry_exporter/src/opentelemetry_exporter.erl
> +            ?LOG_INFO("OTLP grpc export failed with error: ~p", [Reason]),
oh they definitely will

2022-09-28 22:02 UTC, tsloughter commented on apps/opentelemetry_exporter/src/opentelemetry_exporter.erl
> +            ?LOG_INFO("OTLP grpc export failed with error: ~p", [Reason]),
Maybe a `domain` can be used here but then by default all these logs would be lost.. ugh

2022-09-29 23:05 UTC, merged