better support for multiple tracer providers
open-telemetry/opentelemetry-erlang pull request #483
Opened 2022-10-31 23:23 UTC by tsloughter

tracer providers should be able to be started by users and run independently with their own procesors, and multiple of each processor.

The SDK must register a simple_one_for_one that starts tracer providers under the name otel_tracer_provider_sup. Then a global tracer provider is started under the name otel_tracer_server_global to be used when getting tracers that aren't yet cached.

The key thing is that simple and batch processors must return a modified config with `reg_name` set in the map. This is then in the OnStart and OnEnd lambda of functions to run and their configs so it can call them.

My main problem with this strategy is it requires a name and that makes config a little awkward and possibly not compatible with what will be the config file for SDKs that is being worked on -- but if `name` is required for providers and processors in the config file then this is a good solution actually, so I may want to wait on merging this until that is decided.

2022-10-31 23:34 UTC, tsloughter commented
Broke a number of things, unsurprising, and still need tests of when things go wrong (like trying to add a processor with the same name as an existing one, same with providers).

2022-11-01 20:08 UTC, tsloughter commented
I'm getting rid of the naming for processors and maybe providers (at least not required). Will do that in a commit on this PR.

2022-11-01 23:39 UTC, tsloughter commented
I'd like to get rid of the need to name the ets tables in the batch processor but haven't figured that out and not sure there is a way.

The reasons being it currently passes the reference to the ets table to the exporter, if we want to be able to do concurrent exports then we can't be restricted to 2 tables, so can't just wait for it to finish and then reuse that table.

It also benefits from not having to do a `ets:tab2list` in order to pass off the spans to the exporter, instead allows the exporter to go through the ets table content in an order that matches the protobuf schema.

Would also be nice if ets table names could be dropped, or turned into not a named table, but they can't. I think we are stuck with this.

2022-11-03 22:48 UTC, tsloughter commented
This is ready now.

No longer is a name needed from the user. But processors do get a registered name so that they are able to be restarted by the supervisor without a pid change having to happen in the Tracer (which is stored in a persistent term so changing would be terrible).

2022-11-04 00:36 UTC, ferd requested changes
There are a few minor improvements and one major inconsistency I picked up.

2022-11-04 00:36 UTC, ferd commented on apps/opentelemetry/src/otel_batch_processor.erl
> +         %% deprecated
are these deprecated for this app or for the whole API in general? I assume the former and it's a question of structure?

May be worth adding 
```erlang
-deprecated({set_exporter, 1, "use otel_tracer_provider instead"}).
``` 
or whatever the proper call would be?

2022-11-04 00:36 UTC, ferd commented on apps/opentelemetry/src/otel_simple_processor.erl
> +         %% deprecated
same note here; worth using the deprecation attribute?

2022-11-04 00:36 UTC, ferd commented on apps/opentelemetry/src/otel_simple_processor.erl
> +%% @deprecated Please use {@link otel_tracer_provider}
worth using the module directive for these as well I think

2022-11-04 00:36 UTC, ferd commented on apps/opentelemetry/src/otel_simple_processor.erl
> +    gen_statem:call(?REG_NAME(Name), {set_exporter, {Exporter, Options}}).
Given the definition:
```erlang
-define(REG_NAME(Name), list_to_atom(lists:concat([?MODULE, "_", Name]))).
```
Since the type spec specifies an `atom()` for `Name` this `lists:concat/1` call is bound to fail. Something does not work here.

The macro needs to change to have a change to a list first?

2022-11-04 00:36 UTC, ferd commented on apps/opentelemetry/src/otel_tracer_server.erl
> +                case supervisor:start_child(SpanProcessorSup, [ProcessorModule, Config]) of
you can use `try <exp> of ...` here to skip a nested `case`, and it will avoid capturing errors within the matching clauses which are our code.

2022-11-04 00:36 UTC, ferd commented on apps/opentelemetry_api/include/opentelemetry.hrl
> +-define(REG_NAME(Name), list_to_atom(lists:concat([?MODULE, "_", Name]))).
this here thing is used in code with atoms?

2022-11-04 00:36 UTC, ferd commented on apps/opentelemetry_api/src/otel_tracer_provider.erl
> +    ?REG_NAME(Name);
atom here, macro expects strings.

2022-11-04 10:38 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_tracer_provider.erl
> +    ?REG_NAME(Name);
The macro expects anything that works in `lists:concat` which atoms do.

2022-11-04 10:50 UTC, tsloughter commented on apps/opentelemetry_api/include/opentelemetry.hrl
> +-define(REG_NAME(Name), list_to_atom(lists:concat([?MODULE, "_", Name]))).
Yea, `lists:concat` works with strings, atoms, ints, etc

2022-11-04 10:51 UTC, tsloughter commented on apps/opentelemetry/src/otel_batch_processor.erl
> +         %% deprecated
Ah yup, meant to look that up, thought it existed.

2022-11-04 11:16 UTC, tsloughter commented on apps/opentelemetry/src/otel_batch_processor.erl
> +         %% deprecated
And it is deprecated for the whole API in general. We need to get rid of its usage by users (mostly done in tests) because it now requires a bad hack to work -- there is a special "global" name for a processor if it is the only processor on the global tracer provider.

2022-11-04 11:24 UTC, tsloughter commented on apps/opentelemetry/src/otel_tracer_server.erl
> +                case supervisor:start_child(SpanProcessorSup, [ProcessorModule, Config]) of
Updated.

2022-11-04 14:11 UTC, ferd commented on apps/opentelemetry_api/src/otel_tracer_provider.erl
> +    ?REG_NAME(Name);
ah, I had no idea lists:concat handled atoms. Alright then.

2022-11-04 14:12 UTC, ferd approved these changes

2022-11-04 16:05 UTC, tsloughter commented on apps/opentelemetry_api/src/otel_tracer_provider.erl
> +    ?REG_NAME(Name);
Yea, I learned it from reading OTP logger code where it is used this way :)

2022-11-09 19:03 UTC, merged